### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by tmtkzk0823** [anna-cat51/menu_memoire#90]
@anna-cat51 
お疲れ様です！
こちらMVPリリースレビューになります！

### 技術
スクレイピング等を上手に使用して、ユーザーの入力の負担を減らしているなど、カリキュラムでは教わらない分野に挑戦して、技術をユーザーに還元しているような印象を受けました。
大きく気になる箇所はなかったのですが、**少々コメントアウトが多いように感じたので、本リリース前には最低限のコメントアウトに修正しておく**と良さそうです。

### ユーザビリティ
全体的に迷う箇所がすくなく、ユーザー目線での作成ができていると思います。
その中でも細かい点ですが、 以下FBとしてお伝えさせていただきます。

- cookpadのリンクを入力する際、アプリ → cookpadの導線（リンクを押すと別タブで開く）があるとcookpadをたまにしか使用しないユーザーにも親切かと思いました。
- 材料登録の部分で`カンマ(,)`を使用して材料を登録するかと思うのですが、一般的にユーザーは`カンマ(,)`を使用することは少ないかなと思ったので、スクレイピングで取得したデータ以外はフォーム等で個別で登録させるような形をとっても良さそうです。（gem cocoon等を使用）
- また、現状、スクレイピングで材料を取得していると思うのですが、タイトル一緒に取得して、変更したい人には変更をしてもらうような導線でもいいと思います。
- アプリとLINEどちらも使用するアプリケーションかと思うので、Topページの「使い方」の項目を画像などを使って、**使用しているイメージがつくくらい作り込んでもいいかもです**

以上です！

全体的に良くできていて、しっかりユーザーに価値を届けられるアプリケーションになっていると思います！

LGTMです！

上記の内容を本リリース実装するタスクに組み込み、スケジュールを立ててみてください。

スケジュール決まりましたら共有をお願いできればと思います。

また上記レビューに関して、質問などありましたらスレッドに記載いただいてご連絡ください！

**Comment by anna-cat51** [comment]
@tmtkzk0823 とみた講師、レビューありがとうございます！

FBを受けて、2点相談させてください。

レパートリーを登録する際、リンクは用意していることが前提ですが、リンクで遷移できたほうがいいでしょうか？
現在Cookpadのみですが、今後メジャーなサイトを５箇所ほどスクレイピングできるようにとは考えているので、別途使えるサイトとしてのリンク検討しています。

また、レシピサイトのタイトルについて悩ましい部分があります。
個人が投稿する形のレシピサイトのタイトルは通常、目を引くような命名がされるため、スクレイピングで取得することは難しいのではないかなと考えています。
例えば、[こちらのカレーライスなど](https://cookpad.com/recipe/507299)のようなタイトルです。
それと、個人がつけたレシピ名を取得する際、スクレイピングで取得してもよいセーフラインを超えてしまわないか、と懸念点もあります。

こちらについてのアドバイスをいただけると幸いです。

タイトル以外のFBはissueに落とし込み、作成しました。
現時点での本リリース予定日は2月29日を予定しています。
よろしくお願いします✨

**Comment by tmtkzk0823** [comment]
> レパートリーを登録する際、リンクは用意していることが前提ですが、リンクで遷移できたほうがいいでしょうか？
現在Cookpadのみですが、今後メジャーなサイトを５箇所ほどスクレイピングできるようにとは考えているので、別途使えるサイトとしてのリンク検討しています。

上記、「別途、各サイトへの導線を実装する予定」という認識でよろしかったでしょうか？🙇‍♂️（私の方で理解できていなかったらすみません。）

> また、レシピサイトのタイトルについて悩ましい部分があります。
個人が投稿する形のレシピサイトのタイトルは通常、目を引くような命名がされるため、スクレイピングで取得することは難しいのではないかなと考えています。
例えば、[こちらのカレーライスなど](https://cookpad.com/recipe/507299)のようなタイトルです。
それと、個人がつけたレシピ名を取得する際、スクレイピングで取得してもよいセーフラインを超えてしまわないか、と懸念点もあります。

なるほどです！
こちらは上記のような理由があるのであればそのままでいいかと！
ご説明ありがとうございます🙇

**Comment by anna-cat51** [comment]
> 上記、「別途、各サイトへの導線を実装する予定」という認識でよろしかったでしょうか？🙇‍♂️（私の方で理解できていなかったらすみません。）
言葉足らずで申し訳ありません。

Topページの使い方を実装する際に、食材を取得できるサイト　として各種サイトへのリンクを用意する予定です。
また、とみた講師の言う通り登録画面のフォームで各種サイトへの導線があったら使い方に戻らずにどのサイトが利用できるのかもわかりやすくなり親切だと感じたので、
現在　参考にしたURL（現在Cookpadのみ）
としているところで、各種使えるサイトの導線をリンクにして掲載したいと考えていますが、サイトが増えると見栄えが悪くなりそうなのでどうデザインしたらスマートに見えるか、導線がわかりやすいか考え中です。

> なるほどです！
> こちらは上記のような理由があるのであればそのままでいいかと！
> ご説明ありがとうございます🙇

ご指摘ありがとうございます！ではタイトルはそのままで進めていきます。

**Comment by tmtkzk0823** [comment]
ご説明ありがとうございます！

> 各種使えるサイトの導線をリンクにして掲載したいと考えていますが、サイトが増えると見栄えが悪くなりそうなのでどうデザインしたらスマートに見えるか、導線がわかりやすいか考え中です。

一案として、Tailwindを使ってサイドバーを動的に出せそうだったので参考にリンク貼っておきますね！
https://flowbite.com/docs/components/sidebar/#off-canvas-sidebar
この形であれば、サイドバーの中に各レシピサイトへの導線（ボタンやリスト）を配置、別タブで開くようにしても、レバートリー登録フォームへはすぐに戻れそうなイメージがしました！
（一案なので、他の方法があれば、そちらを採用してしまっていいと思います！）

**Comment by anna-cat51** [comment]
サイドバー案、ありがとうございます！
ボタンで開け閉め出来るものはモダンでオシャレですね！
こちらも視野に入れつつイメージを考えて進めてみます。

本リリース予定変わらず2月29日を予定しています。
また詰まったらご相談させてください！
よろしくお願いします。

**Comment by tmtkzk0823** [comment]
承知しました！
実装頑張ってください！
